name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.6'
        
    - name: Build
      run: go build -v ./cmd/gismeteo-cli

    - name: Test
      run: go test -v ./...
